Fixed issue with `mypy` not being run across the celery package
